### ISSUE TITLE
Does on work on Mac, access error

### ISSUE THREAD

**Issue by jsifalda** [polyipseity/obsidian-terminal#2]
Firstly, I had to change the path to the terminal to this: `/System/Applications/Utilities/Terminal.app`. 
Now, I am getting the following error: 
![Obsidian - how-to-commit - wiki - Obsidian v1 1 9 2023-01-13 at 5 14 59 PM](https://user-images.githubusercontent.com/1549390/212367508-7a3f3790-a5ac-43ad-aefb-d0da685e8f53.png)
Access error, any way around it?

**Comment by polyipseity** [comment]
Can you try `/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal`? I made a change to the default terminal on macOS at c027aa700e8c0f08f7fd86f3896e9bbef29acf3a, which should be available from the latest version (2.8.1).

**Comment by jsifalda** [comment]
it seems that the previous issue is fixed, however I am not still able to use the terminal - it opens but nothing else happen.  :( I cannot write anything there

https://capture.dropbox.com/sWjPhAXEKsibRtgr

**Comment by chadblack** [comment]
Using either Terminal or iTerm2, I get this error trying to open a terminal window inside of Obsidian. I have installed Python 3.11 and the two libraries recommended. External terminals will open, but only in the home directory of the computer, not a directory of the vault.

<img width="250" alt="image" src="https://user-images.githubusercontent.com/1526219/212550961-918952f7-8393-4441-8c47-99e6c78d3b4a.png">

**Comment by jsifalda** [comment]
> Using either Terminal or iTerm2, I get this error trying to open a terminal window inside of Obsidian. I have installed Python 3.11 and the two libraries recommended. External terminals will open, but only in the home directory of the computer, not a directory of the vault.
> 
> <img alt="image" width="250" src="https://user-images.githubusercontent.com/1526219/212550961-918952f7-8393-4441-8c47-99e6c78d3b4a.png">

@chadblack to fix this, disable resizer config in plugin settings

**Comment by polyipseity** [comment]
@jsifalda, @chadblack: Great news, the latest version (2.9.0) should fix
the issues with integrated terminals. I have tested it on both Linux and
macOS myself. You only need to install Python 3.10/+ is installed (`psutil`
and `pywinctl` is no longer required on Unix) and reset your settings to
start using them. External terminals are not fixed yet though as it
requires adding new plugin settings.

**Comment by jsifalda** [comment]
sorry @polyipseity , but no luck it seems:

python version:
Python 3.10.8

getting this:
![Obsidian - monorepo - surglogs-fe-wiki - Obsidian v1 1 9 2023-01-21 at 8 53 34 PM](https://user-images.githubusercontent.com/1549390/213884769-0e1f8959-22d7-4f15-9395-0b38bdb381d9.png)

Now i can write inside but not execute the command :(

**Comment by polyipseity** [comment]
@jsifalda: I see that you are stlling using `/System/Applications/
Utilities/Terminal.app/Contents/MacOS/Terminal`. You shoould change it to
from a terminal emulator to a shell like `/bin/zsh`. (because the
integrated terminal itself is already a terminal emulator)

在 2023年1月22日週日 03:54，Jiri Sifalda ***@***.***> 寫道：

**Comment by jsifalda** [comment]
very nice! now, it seems to be working! thanks a lot

**Comment by chadblack** [comment]
Works now! Thanks!
